# Generated by Django 6.0.5 on 2026-06-09 03:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        ('cribado', '0002_alter_cuestionariocribado_fecha_evaluacion_and_more'),
        ('documentos', '0002_documentomedico_estado_and_more'),
        ('pacientes', '0004_paciente_diagnostico_enremision'),
        ('referencias', '0001_initial'),
        ('seguimiento', '0004_add_fase_protocolo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('SINTOMAS_ALARMA', 'Sintomas de alarma'), ('SOSPECHOSO_SIN_REFERENCIA', 'Sospechoso sin referencia'), ('REFERENCIA_SIN_SEGUIMIENTO', 'Referencia sin seguimiento'), ('SEGUIMIENTO_PENDIENTE', 'Seguimiento pendiente o vencido'), ('ALTA_PRIORIDAD_SIN_REVISION', 'Alta prioridad sin revision'), ('DOCUMENTO_PENDIENTE', 'Documento clinico pendiente'), ('CASO_CRITICO', 'Caso critico')], db_index=True, max_length=40, verbose_name='Tipo de alerta')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], db_index=True, default='MEDIA', max_length=10, verbose_name='Nivel de prioridad')),
                ('titulo', models.CharField(max_length=180, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADA', 'Revisada'), ('RESUELTA', 'Resuelta'), ('DESCARTADA', 'Descartada')], db_index=True, default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creacion')),
                ('fecha_limite', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha limite')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revision o cierre')),
                ('comentario_cierre', models.TextField(blank=True, verbose_name='Comentario u observacion de cierre')),
                ('clave_dedupe', models.CharField(db_index=True, editable=False, max_length=140, unique=True, verbose_name='Clave de deduplicacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clinicas', to='casos.casoclinico', verbose_name='Caso relacionado')),
                ('cribado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clinicas', to='cribado.cuestionariocribado', verbose_name='Cribado relacionado')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clinicas', to='documentos.documentomedico', verbose_name='Documento relacionado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_clinicas', to='pacientes.paciente', verbose_name='Paciente')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clinicas', to='referencias.referenciamedica', verbose_name='Referencia relacionada')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clinicas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reviso o resolvio')),
                ('seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clinicas', to='seguimiento.seguimientopaciente', verbose_name='Seguimiento relacionado')),
                ('solicitud_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clinicas', to='documentos.solicituddocumento', verbose_name='Solicitud de documento relacionada')),
            ],
            options={
                'verbose_name': 'Alerta clinica',
                'verbose_name_plural': 'Alertas clinicas',
                'ordering': ['estado', '-prioridad', '-fecha_creacion'],
                'indexes': [models.Index(fields=['paciente', 'estado'], name='alerta_paciente_estado_idx'), models.Index(fields=['prioridad', 'estado'], name='alerta_prioridad_estado_idx'), models.Index(fields=['tipo_alerta'], name='alerta_tipo_idx'), models.Index(fields=['fecha_creacion'], name='alerta_fecha_idx'), models.Index(fields=['fecha_limite'], name='alerta_limite_idx')],
            },
        ),
    ]
