# Generated by Django 6.0.5 on 2026-05-28 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioCribado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación')),
                ('fiebre_persistente', models.BooleanField(default=False, help_text='Temperatura >38°C sin causa aparente por más de 2 semanas', verbose_name='Fiebre persistente (>2 semanas)')),
                ('perdida_peso', models.BooleanField(default=False, verbose_name='Pérdida de peso inexplicable')),
                ('dolor_huesos', models.BooleanField(default=False, verbose_name='Dolor en huesos o articulaciones')),
                ('palidez', models.BooleanField(default=False, verbose_name='Palidez marcada')),
                ('fatiga', models.BooleanField(default=False, verbose_name='Fatiga o cansancio extremo')),
                ('moretones', models.BooleanField(default=False, verbose_name='Moretones sin causa aparente')),
                ('sangrado', models.BooleanField(default=False, help_text='Encías, nariz u otras zonas sin traumatismo', verbose_name='Sangrado espontáneo')),
                ('ganglios', models.BooleanField(default=False, help_text='Linfadenopatía cervical, axilar o inguinal', verbose_name='Ganglios inflamados')),
                ('infecciones_recurrentes', models.BooleanField(default=False, verbose_name='Infecciones recurrentes')),
                ('dolor_cabeza', models.BooleanField(default=False, verbose_name='Dolor de cabeza persistente')),
                ('vomitos', models.BooleanField(default=False, verbose_name='Vómitos matutinos sin causa gastrointestinal')),
                ('masa_abdominal', models.BooleanField(default=False, verbose_name='Masa abdominal palpable')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones clínicas')),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Riesgo bajo'), ('MEDIO', 'Riesgo moderado'), ('ALTO', 'Alerta roja — riesgo alto')], db_index=True, default='BAJO', max_length=10, verbose_name='Nivel de riesgo')),
                ('resultado', models.CharField(choices=[('SIN_SOSPECHA', 'Sin sospecha'), ('SOSPECHA_MODERADA', 'Sospecha moderada'), ('SOSPECHA_ALTA', 'Sospecha alta')], default='SIN_SOSPECHA', max_length=25, verbose_name='Resultado del cribado')),
                ('requiere_referencia', models.BooleanField(default=False, verbose_name='Requiere referencia a especialista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cribados_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Médico evaluador')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cribados', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cuestionario de cribado',
                'verbose_name_plural': 'Cuestionarios de cribado',
                'ordering': ['-fecha_evaluacion'],
                'indexes': [models.Index(fields=['paciente'], name='cribado_paciente_idx'), models.Index(fields=['nivel_riesgo'], name='cribado_nivel_idx'), models.Index(fields=['fecha_evaluacion'], name='cribado_fecha_idx'), models.Index(fields=['requiere_referencia'], name='cribado_referencia_idx')],
            },
        ),
    ]
