# Generated by Django 6.0.1 on 2026-06-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionariocribado',
            name='fecha_evaluacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluacion'),
        ),
        migrations.AlterField(
            model_name='cuestionariocribado',
            name='fiebre_persistente',
            field=models.BooleanField(default=False, help_text='Temperatura >38 C sin causa aparente por mas de 2 semanas', verbose_name='Fiebre persistente (>2 semanas)'),
        ),
        migrations.AlterField(
            model_name='cuestionariocribado',
            name='ganglios',
            field=models.BooleanField(default=False, help_text='Linfadenopatia cervical, axilar o inguinal', verbose_name='Ganglios inflamados'),
        ),
        migrations.AlterField(
            model_name='cuestionariocribado',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cribados_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Medico evaluador'),
        ),
        migrations.AlterField(
            model_name='cuestionariocribado',
            name='nivel_riesgo',
            field=models.CharField(choices=[('BAJO', 'Riesgo bajo'), ('MEDIO', 'Riesgo moderado'), ('ALTO', 'Alerta roja - riesgo alto')], db_index=True, default='BAJO', max_length=10, verbose_name='Nivel de riesgo'),
        ),
        migrations.AlterField(
            model_name='cuestionariocribado',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones clinicas'),
        ),
        migrations.AlterField(
            model_name='cuestionariocribado',
            name='perdida_peso',
            field=models.BooleanField(default=False, verbose_name='Perdida de peso inexplicable'),
        ),
        migrations.AlterField(
            model_name='cuestionariocribado',
            name='sangrado',
            field=models.BooleanField(default=False, help_text='Encias, nariz u otras zonas sin traumatismo', verbose_name='Sangrado espontaneo'),
        ),
        migrations.AlterField(
            model_name='cuestionariocribado',
            name='vomitos',
            field=models.BooleanField(default=False, verbose_name='Vomitos matutinos sin causa gastrointestinal'),
        ),
    ]
