# Generated by Django 6.0.5 on 2026-06-10 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribado', '0002_alter_cuestionariocribado_fecha_evaluacion_and_more'),
        ('pacientes', '0004_paciente_diagnostico_enremision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionariocribado',
            name='leucocoria',
            field=models.BooleanField(default=False, help_text='Pupila blanquecina o reflejo rojo ausente en fotografías — signo principal de retinoblastoma', verbose_name='Leucocoria / reflejo ocular blanquecino'),
        ),
        migrations.AddField(
            model_name='cuestionariocribado',
            name='tipo_cancer_sospechado',
            field=models.CharField(blank=True, choices=[('LEUCEMIA', 'Leucemia'), ('TUMORES_SNC', 'Tumores del SNC'), ('RETINOBLASTOMA', 'Retinoblastoma'), ('TUMOR_WILMS', 'Tumor de Wilms'), ('NEUROBLASTOMA', 'Neuroblastoma'), ('LINFOMA', 'Linfoma'), ('SARCOMA', 'Sarcoma'), ('SIN_DEFINIR', 'Sin definir / General')], db_index=True, help_text='Tipo de cáncer que el médico sospecha según el cuadro clínico', max_length=20, verbose_name='Tipo de cáncer sospechado'),
        ),
        migrations.AddIndex(
            model_name='cuestionariocribado',
            index=models.Index(fields=['tipo_cancer_sospechado'], name='cribado_tipo_cancer_idx'),
        ),
    ]
