# Generated by Django 6.0.5 on 2026-05-28 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadreTutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('TUTOR', 'Tutor legal'), ('OTRO', 'Otro')], default='PADRE', max_length=20, verbose_name='Parentesco')),
                ('direccion', models.TextField(help_text='Dirección completa de residencia', verbose_name='Dirección')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('contacto_emergencia', models.CharField(blank=True, help_text='Nombre del contacto de emergencia', max_length=150, verbose_name='Contacto de emergencia')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de emergencia')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('UNION_LIBRE', 'Unión libre'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a')], max_length=20, verbose_name='Estado civil')),
                ('cantidad_hijos', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad de hijos')),
                ('ingresos_aproximados', models.CharField(blank=True, help_text='Rango mensual en pesos dominicanos (ej. RD$10,000–20,000)', max_length=50, verbose_name='Ingresos aproximados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_padre', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Padre / Tutor',
                'verbose_name_plural': 'Padres / Tutores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provincia'], name='padretutor_provincia_idx')],
            },
        ),
    ]
