# Generated by Django 6.0.5 on 2026-06-01 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_notaclinica'),
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSintoma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('gravedad', models.CharField(choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Severa', 'Severa')], default='Leve', max_length=20, verbose_name='Gravedad')),
                ('sintomas', models.JSONField(default=list, verbose_name='Síntomas reportados')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_sintomas', to='pacientes.paciente', verbose_name='Paciente')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_sintomas', to='padres.padretutor', verbose_name='Tutor reportante')),
            ],
            options={
                'verbose_name': 'Reporte de Síntomas',
                'verbose_name_plural': 'Reportes de Síntomas',
                'ordering': ['-created_at'],
            },
        ),
    ]
