# Generated by Django 6.0.1 on 2026-06-02 20:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0002_reportesintoma'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoEducativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del recurso')),
                ('descripcion', models.TextField(help_text='Contenido educativo del recurso', verbose_name='Descripción')),
                ('icono', models.CharField(default='info', help_text='Nombre del icono (ej. restaurant, favorite, help)', max_length=50, verbose_name='Icono Material Design')),
                ('categoria', models.CharField(choices=[('ALIMENTACION', 'Alimentación'), ('APOYO_EMOCIONAL', 'Apoyo Emocional'), ('PREGUNTAS_FRECUENTES', 'Preguntas Frecuentes'), ('MEDICAMENTOS', 'Medicamentos'), ('ACTIVIDAD_FISICA', 'Actividad Física'), ('HIGIENE', 'Higiene'), ('OTRO', 'Otro')], default='OTRO', max_length=50, verbose_name='Categoría')),
                ('url', models.URLField(blank=True, help_text='URL opcional a recurso externo', verbose_name='Enlace externo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Recurso Educativo',
                'verbose_name_plural': 'Recursos Educativos',
                'ordering': ['categoria', 'titulo'],
                'indexes': [models.Index(fields=['activo', 'categoria'], name='recurso_activo_cat_idx')],
            },
        ),
    ]
