# Generated by Django 6.0.5 on 2026-06-10 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_diagnostico_enremision'),
        ('padres', '0003_add_recurso_educativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTomaMedicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=200, verbose_name='Nombre del medicamento')),
                ('indice', models.PositiveSmallIntegerField(help_text='Posición del medicamento en la lista del día (para identificación)', verbose_name='Índice en la lista del día')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('tomado_a', models.DateTimeField(auto_now_add=True, verbose_name='Marcado como tomado a las')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_toma_medicamento', to='pacientes.paciente', verbose_name='Paciente')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_toma_medicamento', to='padres.padretutor', verbose_name='Tutor que registró')),
            ],
            options={
                'verbose_name': 'Registro de toma de medicamento',
                'verbose_name_plural': 'Registros de toma de medicamentos',
                'ordering': ['-fecha', 'indice'],
                'indexes': [models.Index(fields=['paciente', 'fecha'], name='regtoma_paciente_fecha_idx')],
                'unique_together': {('paciente', 'nombre_medicamento', 'indice', 'fecha')},
            },
        ),
    ]
