# Generated by Django 6.0.5 on 2026-06-20 15:48

import apps.core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0004_registro_toma_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padretutor',
            name='contacto_emergencia',
            field=apps.core.encryption.EncryptedCharField(blank=True, help_text='Nombre del contacto de emergencia', max_length=512, verbose_name='Contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='padretutor',
            name='direccion',
            field=apps.core.encryption.EncryptedTextField(help_text='Dirección completa de residencia', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='padretutor',
            name='telefono_emergencia',
            field=apps.core.encryption.EncryptedCharField(blank=True, max_length=512, verbose_name='Teléfono de emergencia'),
        ),
    ]
