# Generated by Django 6.0.5 on 2026-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0005_alter_padretutor_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='padretutor',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Dominicana', help_text='Nacionalidad legal del padre, madre o tutor responsable', max_length=80, null=True, verbose_name='Nacionalidad'),
        ),
    ]
