# Generated by Django 6.0.5 on 2026-05-28 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada el')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Iniciada por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leido', models.BooleanField(db_index=True, default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='notificaciones.conversacion', verbose_name='Conversación')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS conversacion_paciente_idx ON notificaciones_conversacion (paciente_id)',
            reverse_sql='DROP INDEX IF EXISTS conversacion_paciente_idx',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS mensaje_conversacion_idx ON notificaciones_mensaje (conversacion_id)',
            reverse_sql='DROP INDEX IF EXISTS mensaje_conversacion_idx',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS mensaje_remitente_idx ON notificaciones_mensaje (remitente_id)',
            reverse_sql='DROP INDEX IF EXISTS mensaje_remitente_idx',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS mensaje_leido_idx ON notificaciones_mensaje (leido)',
            reverse_sql='DROP INDEX IF EXISTS mensaje_leido_idx',
        ),
    ]
