# Generated by Django 6.0.5 on 2026-05-30 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL("DROP INDEX IF EXISTS notif_usuario_idx", reverse_sql=""),
        migrations.RunSQL("DROP INDEX IF EXISTS notif_leida_idx", reverse_sql=""),
        migrations.RunSQL("DROP INDEX IF EXISTS notif_created_at_idx", reverse_sql=""),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('mensaje', 'Mensaje'), ('cita', 'Cita'), ('referencia', 'Referencia'), ('sistema', 'Sistema'), ('medicamento', 'Medicamento'), ('sintomas', 'Síntomas')], default='sistema', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('accion_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL de Acción')),
                ('accion_texto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto de Acción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario'], name='notif_usuario_idx'), models.Index(fields=['leida'], name='notif_leida_idx'), models.Index(fields=['created_at'], name='notif_created_at_idx')],
            },
        ),
    ]
