# Generated by Django 6.0.5 on 2026-06-09 04:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notificacion'),
        ('pacientes', '0004_paciente_diagnostico_enremision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoMensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(help_text='Imagen, documento, audio o vídeo', upload_to='mensajes/adjuntos/%Y/%m/', verbose_name='Archivo')),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento (PDF, Word, etc)'), ('audio', 'Audio'), ('video', 'Vídeo'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de archivo')),
                ('nombre_original', models.CharField(blank=True, max_length=255, verbose_name='Nombre original del archivo')),
                ('tamaño_bytes', models.BigIntegerField(default=0, verbose_name='Tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
            ],
            options={
                'verbose_name': 'Adjunto de mensaje',
                'verbose_name_plural': 'Adjuntos de mensajes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteConversacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('miembro', 'Miembro'), ('administrador', 'Administrador'), ('moderador', 'Moderador')], default='miembro', max_length=20, verbose_name='Rol en la conversación')),
                ('silenciada', models.BooleanField(default=False, help_text='Oculta notificaciones pero conserva el historial', verbose_name='Conversación silenciada')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Se unió el')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Se retiró el')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.AlterModelOptions(
            name='conversacion',
            options={'ordering': ['-last_message_at'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AddField(
            model_name='conversacion',
            name='asunto',
            field=models.CharField(blank=True, help_text='Tema principal de la conversación (para grupales)', max_length=200, verbose_name='Asunto'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('archivada', 'Archivada'), ('inactiva', 'Inactiva')], db_index=True, default='activa', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='last_message_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Último mensaje el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversacion',
            name='tipo',
            field=models.CharField(choices=[('privada', 'Privada (Paciente-Médico)'), ('grupal', 'Grupal'), ('expediente', 'Por Expediente')], db_index=True, default='privada', max_length=20, verbose_name='Tipo de conversación'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Eliminado (lógico)'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leida_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Leído el'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='tipo_mensaje',
            field=models.CharField(choices=[('texto', 'Texto'), ('archivo', 'Archivo'), ('imagen', 'Imagen'), ('audio', 'Audio')], db_index=True, default='texto', max_length=20, verbose_name='Tipo de mensaje'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS conversacion_tipo_idx ON notificaciones_conversacion (tipo)', reverse_sql='DROP INDEX IF EXISTS conversacion_tipo_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS conversacion_estado_idx ON notificaciones_conversacion (estado)', reverse_sql='DROP INDEX IF EXISTS conversacion_estado_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS conversacion_last_msg_idx ON notificaciones_conversacion (last_message_at)', reverse_sql='DROP INDEX IF EXISTS conversacion_last_msg_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS mensaje_tipo_idx ON notificaciones_mensaje (tipo_mensaje)', reverse_sql='DROP INDEX IF EXISTS mensaje_tipo_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS mensaje_eliminado_idx ON notificaciones_mensaje (eliminado)', reverse_sql='DROP INDEX IF EXISTS mensaje_eliminado_idx'),
        migrations.AddField(
            model_name='adjuntomensaje',
            name='mensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='notificaciones.mensaje', verbose_name='Mensaje'),
        ),
        migrations.AddField(
            model_name='participanteconversacion',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='notificaciones.conversacion', verbose_name='Conversación'),
        ),
        migrations.AddField(
            model_name='participanteconversacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS adjunto_mensaje_idx ON notificaciones_adjuntomensaje (mensaje_id)', reverse_sql='DROP INDEX IF EXISTS adjunto_mensaje_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS adjunto_tipo_idx ON notificaciones_adjuntomensaje (tipo_archivo)', reverse_sql='DROP INDEX IF EXISTS adjunto_tipo_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS participante_conv_idx ON notificaciones_participanteconversacion (conversacion_id)', reverse_sql='DROP INDEX IF EXISTS participante_conv_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS participante_user_idx ON notificaciones_participanteconversacion (usuario_id)', reverse_sql='DROP INDEX IF EXISTS participante_user_idx'),
        migrations.AlterUniqueTogether(
            name='participanteconversacion',
            unique_together={('conversacion', 'usuario')},
        ),
    ]
