# Generated by Django 6.0.5 on 2026-06-09 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notificaciones', '0003_adjuntomensaje_participanteconversacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RemoveIndex(
            model_name='notificacion',
            name='notif_leida_idx',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='archivada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivada'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='clave_dedupe',
            field=models.CharField(blank=True, db_index=True, max_length=180, null=True, unique=True, verbose_name='Clave de deduplicacion'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='contenttypes.contenttype', verbose_name='Tipo de objeto relacionado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='icono_nombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icono visual'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='modulo',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Modulo relacionado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='objeto_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID de objeto relacionado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], db_index=True, default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizada el'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='accion_texto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto de accion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='accion_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de accion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Leida'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('referencia', 'Referencia'), ('cita', 'Cita'), ('seguimiento', 'Seguimiento'), ('alerta', 'Alerta'), ('alerta_clinica', 'Alerta clinica'), ('mensaje', 'Mensaje'), ('reporte', 'Reporte'), ('documento', 'Documento'), ('paciente', 'Paciente'), ('cribado', 'Cribado'), ('medicamento', 'Medicamento'), ('sintomas', 'Sintomas')], db_index=True, default='sistema', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(max_length=180, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destinatario'),
        ),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS notif_user_leida_idx ON notificaciones_notificacion (usuario_id, leida)', reverse_sql='DROP INDEX IF EXISTS notif_user_leida_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS notif_user_arch_idx ON notificaciones_notificacion (usuario_id, archivada)', reverse_sql='DROP INDEX IF EXISTS notif_user_arch_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS notif_tipo_idx ON notificaciones_notificacion (tipo)', reverse_sql='DROP INDEX IF EXISTS notif_tipo_idx'),
        migrations.RunSQL(sql='CREATE INDEX IF NOT EXISTS notif_prioridad_idx ON notificaciones_notificacion (prioridad)', reverse_sql='DROP INDEX IF EXISTS notif_prioridad_idx'),
    ]
