CATALOGO_LABORATORIO = [
    {
        'nombre': 'Hemograma, diferencial y frotis',
        'categoria': 'Hematologia',
        'descripcion': 'Parametros hematologicos basicos y revision morfologica periferica.',
        'parametros': [
            {'nombre': 'Hemoglobina', 'unidad': 'g/dL', 'min': '9.0', 'max': '19.9', 'alerta_sistema': 'Anemia o hemoconcentracion segun contexto clinico.'},
            {'nombre': 'Hematocrito', 'unidad': '%', 'min': '28', 'max': '65'},
            {'nombre': 'Eritrocitos / RBC', 'unidad': 'millones/uL', 'min': '2.7', 'max': '5.9'},
            {'nombre': 'Leucocitos / WBC', 'unidad': 'x10^3/uL', 'min': '4.5', 'max': '30'},
            {'nombre': 'Neutrofilos absolutos / ANC', 'unidad': 'x10^3/uL', 'min': '1.0', 'max': '8.3', 'alerta_sistema': 'Neutropenia o neutrofilia; correlacionar con fiebre y quimioterapia.', 'alerta_critica': True},
            {'nombre': 'Neutrofilos', 'unidad': '%', 'min': '10', 'max': '70'},
            {'nombre': 'Linfocitos absolutos', 'unidad': 'x10^3/uL', 'min': '0.97', 'max': '9.14'},
            {'nombre': 'Linfocitos', 'unidad': '%', 'min': '15', 'max': '86'},
            {'nombre': 'Monocitos absolutos', 'unidad': 'x10^3/uL', 'min': '0.18', 'max': '1.77'},
            {'nombre': 'Eosinofilos absolutos', 'unidad': 'x10^3/uL', 'min': '0', 'max': '0.82'},
            {'nombre': 'Basofilos absolutos', 'unidad': 'x10^3/uL', 'min': '0', 'max': '0.11'},
            {'nombre': 'Plaquetas', 'unidad': 'x10^3/uL', 'min': '150', 'max': '450', 'alerta_sistema': 'Trombocitopenia o trombocitosis; vigilar sangrado o riesgo trombotico.', 'alerta_critica': True},
            {'nombre': 'VCM / MCV', 'unidad': 'fL', 'min': '70', 'max': '123'},
            {'nombre': 'HCM / MCH', 'unidad': 'pg', 'min': '23', 'max': '37'},
            {'nombre': 'CHCM / MCHC', 'unidad': 'g/dL', 'min': '28', 'max': '36'},
            {'nombre': 'RDW', 'unidad': '%', 'min': '11.5', 'max': '14.5'},
            {'nombre': 'Reticulocitos', 'unidad': '%', 'min': '0.5', 'max': '2.5'},
            {'nombre': 'Blastos en sangre periferica', 'unidad': '%', 'min': '0', 'max': '0', 'alerta_sistema': 'Presencia de blastos en sangre periferica requiere revision urgente.', 'alerta_critica': True},
            {'nombre': 'Metamielocitos / Mielocitos / Promielocitos', 'unidad': '%', 'min': '0', 'max': '0', 'alerta_sistema': 'Formas inmaduras circulantes; correlacionar con frotis.'},
            {'nombre': 'Frotis periferico', 'unidad': 'texto', 'referencia_texto': 'No aplica', 'tipo_valor': 'texto', 'requiere_comentario': True, 'comentario_sugerido': 'Describir morfologia eritrocitaria, leucocitaria, plaquetaria y hallazgos anormales.', 'alerta_sistema': 'Requiere interpretacion morfologica.'},
        ],
    },
    {
        'nombre': 'Quimica sanguinea y metabolismo',
        'categoria': 'Quimica sanguinea',
        'descripcion': 'Bioquimica sanguinea, electrolitos, funcion renal, hepatica y metabolismo.',
        'parametros': [
            {'nombre': 'Glucosa en ayunas', 'unidad': 'mg/dL', 'min': '70', 'max': '99'},
            {'nombre': 'Urea / BUN', 'unidad': 'mg/dL', 'min': '5', 'max': '18'},
            {'nombre': 'Creatinina', 'unidad': 'mg/dL', 'min': '0.2', 'max': '1.0'},
            {'nombre': 'Sodio', 'unidad': 'mmol/L', 'min': '135', 'max': '145', 'alerta_sistema': 'Alteracion significativa de sodio puede ser critica.', 'alerta_critica': True},
            {'nombre': 'Potasio', 'unidad': 'mmol/L', 'min': '3.5', 'max': '5.2', 'alerta_sistema': 'Alteracion de potasio puede comprometer ritmo cardiaco.', 'alerta_critica': True},
            {'nombre': 'Cloro', 'unidad': 'mmol/L', 'min': '98', 'max': '107'},
            {'nombre': 'CO2 total / Bicarbonato', 'unidad': 'mmol/L', 'min': '20', 'max': '28'},
            {'nombre': 'Calcio total', 'unidad': 'mg/dL', 'min': '8.8', 'max': '10.8'},
            {'nombre': 'Calcio ionizado', 'unidad': 'mmol/L', 'min': '1.12', 'max': '1.32'},
            {'nombre': 'Fosforo', 'unidad': 'mg/dL', 'min': '3.0', 'max': '6.5'},
            {'nombre': 'Magnesio', 'unidad': 'mg/dL', 'min': '1.7', 'max': '2.3'},
            {'nombre': 'Acido urico', 'unidad': 'mg/dL', 'min': '2.0', 'max': '5.5', 'alerta_sistema': 'Elevar vigilancia ante riesgo de lisis tumoral.'},
            {'nombre': 'LDH / DHL', 'unidad': 'U/L', 'min': '120', 'max': '300'},
            {'nombre': 'Albumina', 'unidad': 'g/dL', 'min': '3.1', 'max': '5.6'},
            {'nombre': 'Proteinas totales', 'unidad': 'g/dL', 'min': '5.5', 'max': '8.0'},
            {'nombre': 'Bilirrubina total', 'unidad': 'mg/dL', 'min': '0.0', 'max': '1.2'},
            {'nombre': 'Bilirrubina directa/conjugada', 'unidad': 'mg/dL', 'min': '0.0', 'max': '0.3'},
            {'nombre': 'Bilirrubina indirecta', 'unidad': 'mg/dL', 'min': '0.1', 'max': '0.8'},
            {'nombre': 'AST / TGO', 'unidad': 'U/L', 'min': '5', 'max': '140'},
            {'nombre': 'ALT / TGP', 'unidad': 'U/L', 'min': '5', 'max': '45'},
            {'nombre': 'Fosfatasa alcalina', 'unidad': 'U/L', 'min': '50', 'max': '560'},
            {'nombre': 'GGT', 'unidad': 'U/L', 'min': '5', 'max': '168'},
            {'nombre': 'Amilasa', 'unidad': 'U/L', 'min': '0', 'max': '110'},
            {'nombre': 'Lipasa', 'unidad': 'U/L', 'min': '0', 'max': '60'},
        ],
    },
    {
        'nombre': 'Inflamacion, infeccion y estado critico',
        'categoria': 'Inflamacion e infeccion',
        'descripcion': 'Marcadores inflamatorios, sepsis, estado critico y sindromes hiperinflamatorios.',
        'parametros': [
            {'nombre': 'PCR / Proteina C reactiva', 'unidad': 'mg/L', 'min': '0', 'max': '10'},
            {'nombre': 'VSG / ESR', 'unidad': 'mm/h', 'min': '1', 'max': '20'},
            {'nombre': 'Procalcitonina', 'unidad': 'ng/mL', 'min': '0', 'max': '0.5', 'alerta_sistema': 'Puede sugerir infeccion bacteriana severa si se eleva.'},
            {'nombre': 'Ferritina', 'unidad': 'ng/mL', 'min': '7', 'max': '140', 'alerta_sistema': 'Elevar vigilancia ante inflamacion intensa o HLH segun contexto.'},
            {'nombre': 'Lactato', 'unidad': 'mmol/L', 'min': '0.5', 'max': '2.2', 'alerta_sistema': 'Lactato elevado puede indicar hipoperfusion o sepsis.', 'alerta_critica': True},
            {'nombre': 'Fibrinogeno', 'unidad': 'mg/dL', 'min': '150', 'max': '400'},
            {'nombre': 'Trigliceridos', 'unidad': 'mg/dL', 'min': '0', 'max': '150'},
            {'nombre': 'Dimero D', 'unidad': 'ug/mL FEU', 'min': '0', 'max': '0.5'},
        ],
    },
    {
        'nombre': 'Coagulacion y hemostasia',
        'categoria': 'Coagulacion',
        'descripcion': 'Pruebas de coagulacion, factores y hemostasia.',
        'parametros': [
            {'nombre': 'TP / PT', 'unidad': 'segundos', 'min': '11', 'max': '14'},
            {'nombre': 'INR', 'unidad': 'ratio', 'min': '0.8', 'max': '1.2'},
            {'nombre': 'TTPa / aPTT', 'unidad': 'segundos', 'min': '25', 'max': '37'},
            {'nombre': 'Tiempo de trombina', 'unidad': 'segundos', 'min': '18.7', 'max': '25.5'},
            {'nombre': 'Fibrinogeno', 'unidad': 'mg/dL', 'min': '131', 'max': '405'},
            {'nombre': 'Dimero D', 'unidad': 'ug/mL FEU', 'min': '0', 'max': '0.5'},
            {'nombre': 'Antitrombina III', 'unidad': '%', 'min': '87', 'max': '145'},
            {'nombre': 'Proteina C', 'unidad': '%', 'min': '81', 'max': '150'},
            {'nombre': 'Proteina S funcional', 'unidad': '%', 'min': '61', 'max': '140'},
            {'nombre': 'vWF actividad', 'unidad': '%', 'min': '47', 'max': '151'},
            {'nombre': 'vWF antigeno', 'unidad': '%', 'min': '35', 'max': '197'},
            {'nombre': 'Factor VIII', 'unidad': '%', 'min': '49', 'max': '191'},
            {'nombre': 'Factor IX', 'unidad': '%', 'min': '52', 'max': '112'},
        ],
    },
    {
        'nombre': 'Orina y funcion renal complementaria',
        'categoria': 'Orina y renal',
        'descripcion': 'Uroanalisis, sedimento y funcion renal complementaria.',
        'parametros': [
            {'nombre': 'Densidad urinaria', 'unidad': 'valor', 'min': '1.005', 'max': '1.030'},
            {'nombre': 'pH urinario', 'unidad': 'valor', 'min': '5.0', 'max': '8.0'},
            {'nombre': 'Proteinas en orina', 'unidad': 'mg/dL o tira', 'referencia_texto': 'Negativo', 'tipo_valor': 'resultado'},
            {'nombre': 'Sangre en orina', 'unidad': 'tira', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'Glucosa en orina', 'unidad': 'tira', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'Cetonas', 'unidad': 'tira', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'Leucocitos en orina', 'unidad': 'tira', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'Nitritos', 'unidad': 'tira', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'RBC en sedimento', 'unidad': '/campo HPF', 'min': '0', 'max': '2'},
            {'nombre': 'WBC en sedimento', 'unidad': '/campo HPF', 'min': '0', 'max': '5'},
            {'nombre': 'Relacion proteina/creatinina', 'unidad': 'mg/mg', 'min': '0', 'max': '0.2'},
        ],
    },
    {
        'nombre': 'Marcadores tumorales en sangre/orina',
        'categoria': 'Marcadores tumorales',
        'descripcion': 'Marcadores tumorales sericos y urinarios usados en oncologia pediatrica.',
        'parametros': [
            {'nombre': 'AFP / Alfa-fetoproteina', 'unidad': 'ng/mL', 'min': '0', 'max': '10'},
            {'nombre': 'beta-hCG cuantitativa', 'unidad': 'IU/L', 'min': '0', 'max': '5'},
            {'nombre': 'LDH', 'unidad': 'U/L', 'min': '120', 'max': '300'},
            {'nombre': 'CEA', 'unidad': 'ng/mL', 'min': '0', 'max': '3'},
            {'nombre': 'CA-125', 'unidad': 'U/mL', 'min': '0', 'max': '35'},
            {'nombre': 'CA 19-9', 'unidad': 'U/mL', 'min': '0', 'max': '37'},
            {'nombre': 'NSE / Enolasa neuronal especifica', 'unidad': 'ng/mL', 'min': '0', 'max': '16.3'},
            {'nombre': 'Cromogranina A', 'unidad': 'ng/mL', 'min': '0', 'max': '93'},
            {'nombre': 'VMA urinario', 'unidad': 'mg/g creatinina', 'referencia_texto': 'Segun edad', 'tipo_valor': 'resultado'},
            {'nombre': 'HVA urinario', 'unidad': 'mg/g creatinina', 'referencia_texto': 'Segun edad', 'tipo_valor': 'resultado'},
            {'nombre': 'Metanefrinas plasma/orina', 'unidad': 'nmol/L o ug/24h', 'referencia_texto': 'Segun edad', 'tipo_valor': 'resultado'},
            {'nombre': 'Catecolaminas urinarias', 'unidad': 'ug/24h', 'referencia_texto': 'Segun edad', 'tipo_valor': 'resultado'},
            {'nombre': 'Tiroglobulina', 'unidad': 'ng/mL', 'referencia_texto': 'No aplica', 'tipo_valor': 'resultado'},
            {'nombre': 'Calcitonina', 'unidad': 'pg/mL', 'min': '0', 'max': '10'},
            {'nombre': 'Beta-2 microglobulina', 'unidad': 'mg/L', 'min': '0.8', 'max': '2.4'},
            {'nombre': 'Inhibina A/B', 'unidad': 'pg/mL', 'referencia_texto': 'Segun edad/sexo', 'tipo_valor': 'resultado'},
        ],
    },
    {
        'nombre': 'Liquido cefalorraquideo / LCR',
        'categoria': 'LCR',
        'descripcion': 'Parametros de LCR, citologia y citometria.',
        'parametros': [
            {'nombre': 'Celulas nucleadas en LCR', 'unidad': 'celulas/uL', 'min': '0', 'max': '5'},
            {'nombre': 'Glucosa en LCR', 'unidad': 'mg/dL', 'min': '32', 'max': '82'},
            {'nombre': 'Proteinas en LCR', 'unidad': 'mg/dL', 'min': '15', 'max': '120'},
            {'nombre': 'Lactato en LCR', 'unidad': 'mmol/L', 'min': '0.0', 'max': '3.3'},
            {'nombre': 'RBC en LCR', 'unidad': 'celulas/uL', 'min': '0', 'max': '0'},
            {'nombre': 'Blastos/celulas malignas en LCR', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'alerta_sistema': 'Resultado positivo requiere revision urgente.', 'alerta_critica': True},
            {'nombre': 'Citologia de LCR', 'unidad': 'texto', 'referencia_texto': 'No aplica', 'tipo_valor': 'texto', 'requiere_comentario': True, 'comentario_sugerido': 'Registrar celularidad, hallazgos morfologicos y presencia/ausencia de celulas malignas.', 'alerta_sistema': 'Requiere interpretacion.'},
            {'nombre': 'Citometria de flujo en LCR', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'requiere_comentario': True, 'comentario_sugerido': 'Documentar inmunofenotipo y conclusion.', 'alerta_sistema': 'Positividad sugiere compromiso de LCR.', 'alerta_critica': True},
            {'nombre': 'AFP en LCR', 'unidad': 'ng/mL', 'min': '0', 'max': '1.5'},
            {'nombre': 'beta-hCG en LCR', 'unidad': 'IU/L', 'min': '0', 'max': '5'},
        ],
    },
    {
        'nombre': 'Medula osea, hematologia avanzada y citometria',
        'categoria': 'Medula osea',
        'descripcion': 'Aspirado, biopsia, citometria, citogenetica y enfermedad minima residual.',
        'parametros': [
            {'nombre': 'Aspirado de medula osea', 'unidad': 'texto', 'referencia_texto': 'No aplica', 'tipo_valor': 'texto', 'requiere_comentario': True, 'comentario_sugerido': 'Describir celularidad, morfologia, recuento diferencial y conclusion.'},
            {'nombre': 'Biopsia de medula osea', 'unidad': 'texto', 'referencia_texto': 'No aplica', 'tipo_valor': 'texto', 'requiere_comentario': True, 'comentario_sugerido': 'Describir celularidad, fibrosis, infiltracion y conclusion.'},
            {'nombre': 'Blastos en medula osea', 'unidad': '%', 'min': '0', 'max': '5', 'alerta_sistema': 'Blastos elevados requieren correlacion diagnostica.', 'alerta_critica': True},
            {'nombre': 'Celularidad medular', 'unidad': '%', 'referencia_texto': 'Variable', 'tipo_valor': 'resultado'},
            {'nombre': 'EMR/MRD por citometria', 'unidad': '%', 'min': '0', 'max': '0.01', 'alerta_sistema': 'EMR positiva requiere evaluacion terapeutica.', 'alerta_critica': True},
            {'nombre': 'Citometria de flujo - linaje B', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'requiere_comentario': True},
            {'nombre': 'Citometria de flujo - linaje T', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'requiere_comentario': True},
            {'nombre': 'Citometria de flujo - linaje mieloide', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'requiere_comentario': True},
            {'nombre': 'Cariotipo / citogenetica', 'unidad': 'resultado', 'referencia_texto': 'Normal', 'tipo_valor': 'resultado', 'requiere_comentario': True},
            {'nombre': 'FISH', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'requiere_comentario': True},
            {'nombre': 'PCR molecular', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'requiere_comentario': True},
            {'nombre': 'BCR-ABL1', 'unidad': '% IS o resultado', 'min': '0', 'max': '0', 'alerta_sistema': 'Deteccion positiva requiere valoracion especializada.', 'alerta_critica': True},
            {'nombre': 'ETV6-RUNX1', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'KMT2A / MLL rearrangement', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'alerta_critica': True},
            {'nombre': 'RUNX1-RUNX1T1', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'CBFB-MYH11', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'PML-RARA', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'alerta_sistema': 'Positivo requiere atencion urgente.', 'alerta_critica': True},
            {'nombre': 'FLT3, NPM1, CEBPA', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
        ],
    },
    {
        'nombre': 'Patologia, biopsia e inmunohistoquimica',
        'categoria': 'Patologia',
        'descripcion': 'Diagnostico histologico, inmunohistoquimica y caracterizacion tumoral.',
        'parametros': [
            {'nombre': 'Diagnostico histologico', 'unidad': 'texto', 'referencia_texto': 'No aplica', 'tipo_valor': 'texto', 'requiere_comentario': True, 'comentario_sugerido': 'Registrar diagnostico anatomopatologico completo.'},
            {'nombre': 'Tipo histologico', 'unidad': 'texto', 'referencia_texto': 'No aplica', 'tipo_valor': 'texto', 'requiere_comentario': True},
            {'nombre': 'Grado tumoral', 'unidad': 'grado', 'referencia_texto': 'No aplica', 'tipo_valor': 'resultado', 'requiere_comentario': True},
            {'nombre': 'Ki-67', 'unidad': '%', 'min': '0', 'max': '100'},
            {'nombre': 'Margenes quirurgicos', 'unidad': 'resultado', 'referencia_texto': 'Negativo/libre', 'tipo_valor': 'resultado', 'alerta_sistema': 'Margenes comprometidos requieren evaluacion multidisciplinaria.', 'alerta_critica': True},
            {'nombre': 'Necrosis tumoral', 'unidad': '%', 'min': '0', 'max': '100'},
            {'nombre': 'Invasion vascular', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'Invasion linfatica', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'Ganglios positivos', 'unidad': 'numero', 'min': '0', 'max': '0', 'alerta_critica': True},
            {'nombre': 'Estadio', 'unidad': 'I-IV/TNM', 'referencia_texto': 'No aplica', 'tipo_valor': 'resultado', 'requiere_comentario': True},
            {'nombre': 'CD45', 'unidad': 'resultado', 'referencia_texto': 'Negativo/positivo esperado', 'tipo_valor': 'resultado'},
            {'nombre': 'CD3', 'unidad': 'resultado', 'referencia_texto': 'Negativo/positivo esperado', 'tipo_valor': 'resultado'},
            {'nombre': 'CD20 / CD19', 'unidad': 'resultado', 'referencia_texto': 'Negativo/positivo esperado', 'tipo_valor': 'resultado'},
            {'nombre': 'CD10, CD34, TdT', 'unidad': 'resultado', 'referencia_texto': 'Negativo/positivo esperado', 'tipo_valor': 'resultado'},
            {'nombre': 'MPO', 'unidad': 'resultado', 'referencia_texto': 'Negativo/positivo esperado', 'tipo_valor': 'resultado'},
            {'nombre': 'Desmina, Myogenin, MyoD1', 'unidad': 'resultado', 'referencia_texto': 'Negativo/positivo esperado', 'tipo_valor': 'resultado'},
            {'nombre': 'Synaptophysin, Chromogranin', 'unidad': 'resultado', 'referencia_texto': 'Negativo/positivo esperado', 'tipo_valor': 'resultado'},
            {'nombre': 'WT1', 'unidad': 'resultado', 'referencia_texto': 'Negativo/positivo esperado', 'tipo_valor': 'resultado'},
            {'nombre': 'GFAP', 'unidad': 'resultado', 'referencia_texto': 'Negativo/positivo esperado', 'tipo_valor': 'resultado'},
            {'nombre': 'INI1/SMARCB1', 'unidad': 'resultado', 'referencia_texto': 'Conservado', 'tipo_valor': 'resultado'},
            {'nombre': 'ALK', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
        ],
    },
    {
        'nombre': 'Genetica, biomarcadores moleculares e inmunoterapia',
        'categoria': 'Genetica molecular',
        'descripcion': 'Pruebas geneticas, biomarcadores moleculares y predictores terapeuticos.',
        'parametros': [
            {'nombre': 'Panel NGS tumoral', 'unidad': 'resultado', 'referencia_texto': 'No detectable', 'tipo_valor': 'resultado', 'requiere_comentario': True},
            {'nombre': 'Secuenciacion de ADN tumoral', 'unidad': 'resultado', 'referencia_texto': 'No detectable', 'tipo_valor': 'resultado', 'requiere_comentario': True},
            {'nombre': 'Secuenciacion de ARN/fusiones', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'resultado', 'requiere_comentario': True},
            {'nombre': 'TMB / carga mutacional tumoral', 'unidad': 'mut/Mb', 'min': '0', 'max': '10'},
            {'nombre': 'MSI', 'unidad': 'resultado', 'referencia_texto': 'Estable', 'tipo_valor': 'resultado'},
            {'nombre': 'MMR por IHQ', 'unidad': 'resultado', 'referencia_texto': 'Conservado', 'tipo_valor': 'resultado'},
            {'nombre': 'NTRK fusion', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'ALK fusion/mutacion', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'ROS1', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'BRAF V600E', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'RAS / KRAS / NRAS', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'MYCN amplificacion', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'Alteracion 1p / 11q', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'TP53', 'unidad': 'resultado', 'referencia_texto': 'Sin mutacion', 'tipo_valor': 'resultado'},
            {'nombre': 'RB1', 'unidad': 'resultado', 'referencia_texto': 'Sin mutacion', 'tipo_valor': 'resultado'},
            {'nombre': 'DICER1', 'unidad': 'resultado', 'referencia_texto': 'Sin mutacion', 'tipo_valor': 'resultado'},
            {'nombre': 'NF1', 'unidad': 'resultado', 'referencia_texto': 'Sin mutacion', 'tipo_valor': 'resultado'},
            {'nombre': 'APC', 'unidad': 'resultado', 'referencia_texto': 'Sin mutacion', 'tipo_valor': 'resultado'},
            {'nombre': 'BRCA1/BRCA2', 'unidad': 'resultado', 'referencia_texto': 'Sin mutacion', 'tipo_valor': 'resultado'},
        ],
    },
    {
        'nombre': 'Inmunidad, infecciones virales y preparacion para tratamiento',
        'categoria': 'Inmunidad e infecciones',
        'descripcion': 'Estado inmunitario, serologias y cargas virales relevantes antes o durante tratamiento.',
        'parametros': [
            {'nombre': 'IgG', 'unidad': 'mg/dL', 'min': '300', 'max': '1600'},
            {'nombre': 'IgA', 'unidad': 'mg/dL', 'min': '5', 'max': '300'},
            {'nombre': 'IgM', 'unidad': 'mg/dL', 'min': '20', 'max': '200'},
            {'nombre': 'CD3 absoluto', 'unidad': 'celulas/uL', 'min': '700', 'max': '4200'},
            {'nombre': 'CD4 absoluto', 'unidad': 'celulas/uL', 'min': '300', 'max': '2400'},
            {'nombre': 'CD8 absoluto', 'unidad': 'celulas/uL', 'min': '200', 'max': '1600'},
            {'nombre': 'CD19 absoluto', 'unidad': 'celulas/uL', 'min': '100', 'max': '1300'},
            {'nombre': 'NK absoluto', 'unidad': 'celulas/uL', 'min': '90', 'max': '900'},
            {'nombre': 'VIH Ag/Ac', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'alerta_critica': True},
            {'nombre': 'HBsAg', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'alerta_critica': True},
            {'nombre': 'Anti-HBc', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo'},
            {'nombre': 'Anti-HBs', 'unidad': 'mIU/mL', 'min': '10', 'referencia_texto': 'No aplica'},
            {'nombre': 'Hepatitis C Ac/PCR', 'unidad': 'resultado', 'referencia_texto': 'Negativo', 'tipo_valor': 'positivo_negativo', 'alerta_critica': True},
            {'nombre': 'EBV PCR/carga viral', 'unidad': 'copias/mL', 'referencia_texto': 'No detectable', 'tipo_valor': 'resultado'},
            {'nombre': 'CMV PCR/carga viral', 'unidad': 'copias/mL', 'referencia_texto': 'No detectable', 'tipo_valor': 'resultado'},
        ],
    },
    {
        'nombre': 'Signos vitales, medidas corporales y seguimiento oncologico',
        'categoria': 'Seguimiento clinico',
        'descripcion': 'Variables antropometricas, signos vitales y escalas funcionales de seguimiento.',
        'parametros': [
            {'nombre': 'Peso', 'unidad': 'kg', 'referencia_texto': 'No aplica'},
            {'nombre': 'Talla', 'unidad': 'cm', 'referencia_texto': 'No aplica'},
            {'nombre': 'Superficie corporal / BSA', 'unidad': 'm2', 'referencia_texto': 'No aplica'},
            {'nombre': 'Temperatura', 'unidad': 'C', 'min': '36.0', 'max': '37.5', 'alerta_sistema': 'Fiebre si temperatura >= 38 C; considerar neutropenia febril.', 'alerta_critica': True},
            {'nombre': 'Frecuencia cardiaca', 'unidad': 'lpm', 'referencia_texto': 'Variable segun edad'},
            {'nombre': 'Frecuencia respiratoria', 'unidad': 'rpm', 'referencia_texto': 'Variable segun edad'},
            {'nombre': 'Presion arterial', 'unidad': 'mmHg', 'referencia_texto': 'Variable segun edad/talla', 'tipo_valor': 'resultado'},
            {'nombre': 'Saturacion O2', 'unidad': '%', 'min': '95', 'max': '100', 'alerta_sistema': 'Hipoxemia si esta por debajo de referencia.', 'alerta_critica': True},
            {'nombre': 'Dolor', 'unidad': 'escala 0-10', 'min': '0', 'max': '10'},
            {'nombre': 'Estado ECOG/Lansky/Karnofsky', 'unidad': '% o escala', 'referencia_texto': 'No aplica', 'tipo_valor': 'resultado', 'requiere_comentario': True},
        ],
    },
]
