PLANTILLAS_EXAMEN = {
    'HEMOGRAMA': [
        {'parametro': 'Hemoglobina', 'unidad': 'g/dL', 'ref_min': '11.0', 'ref_max': '16.0'},
        {'parametro': 'Hematocrito', 'unidad': '%', 'ref_min': '33', 'ref_max': '47'},
        {'parametro': 'Leucocitos', 'unidad': 'x10³/μL', 'ref_min': '4.5', 'ref_max': '13.0'},
        {'parametro': 'Neutrófilos', 'unidad': '%', 'ref_min': '40', 'ref_max': '70'},
        {'parametro': 'Linfocitos', 'unidad': '%', 'ref_min': '20', 'ref_max': '50'},
        {'parametro': 'Plaquetas', 'unidad': 'x10³/μL', 'ref_min': '150', 'ref_max': '450'},
        {'parametro': 'VCM', 'unidad': 'fL', 'ref_min': '70', 'ref_max': '90'},
        {'parametro': 'CHCM', 'unidad': 'g/dL', 'ref_min': '32', 'ref_max': '36'},
    ],
    'QUIMICA': [
        {'parametro': 'Glucosa', 'unidad': 'mg/dL', 'ref_min': '70', 'ref_max': '100'},
        {'parametro': 'Urea', 'unidad': 'mg/dL', 'ref_min': '7', 'ref_max': '20'},
        {'parametro': 'Creatinina', 'unidad': 'mg/dL', 'ref_min': '0.3', 'ref_max': '1.2'},
        {'parametro': 'TGO (AST)', 'unidad': 'U/L', 'ref_min': '10', 'ref_max': '40'},
        {'parametro': 'TGP (ALT)', 'unidad': 'U/L', 'ref_min': '7', 'ref_max': '56'},
        {'parametro': 'Bilirrubina total', 'unidad': 'mg/dL', 'ref_min': '0.1', 'ref_max': '1.0'},
        {'parametro': 'Proteínas totales', 'unidad': 'g/dL', 'ref_min': '6.0', 'ref_max': '8.0'},
        {'parametro': 'LDH', 'unidad': 'U/L', 'ref_min': '120', 'ref_max': '330'},
        {'parametro': 'Ácido úrico', 'unidad': 'mg/dL', 'ref_min': '2.5', 'ref_max': '7.0'},
        {'parametro': 'Calcio', 'unidad': 'mg/dL', 'ref_min': '8.5', 'ref_max': '10.5'},
        {'parametro': 'Fósforo', 'unidad': 'mg/dL', 'ref_min': '4.0', 'ref_max': '6.5'},
    ],
    'COAGULACION': [
        {'parametro': 'TP', 'unidad': 'seg', 'ref_min': '11', 'ref_max': '14'},
        {'parametro': 'TTP', 'unidad': 'seg', 'ref_min': '25', 'ref_max': '35'},
        {'parametro': 'INR', 'unidad': '', 'ref_min': '0.8', 'ref_max': '1.2'},
        {'parametro': 'Fibrinógeno', 'unidad': 'mg/dL', 'ref_min': '200', 'ref_max': '400'},
        {'parametro': 'Dímero D', 'unidad': 'μg/mL', 'ref_min': '', 'ref_max': '0.5'},
    ],
    'MARCADORES': [
        {'parametro': 'AFP (Alfa-fetoproteína)', 'unidad': 'ng/mL', 'ref_min': '', 'ref_max': '10'},
        {'parametro': 'Beta-HCG', 'unidad': 'mIU/mL', 'ref_min': '', 'ref_max': '5'},
        {'parametro': 'LDH', 'unidad': 'U/L', 'ref_min': '120', 'ref_max': '330'},
        {'parametro': 'NSE (Enolasa)', 'unidad': 'μg/L', 'ref_min': '', 'ref_max': '12'},
        {'parametro': 'CEA', 'unidad': 'ng/mL', 'ref_min': '', 'ref_max': '2.5'},
        {'parametro': 'Ferritina', 'unidad': 'ng/mL', 'ref_min': '12', 'ref_max': '200'},
    ],
    'ORINA': [
        {'parametro': 'pH', 'unidad': '', 'ref_min': '4.5', 'ref_max': '8.0'},
        {'parametro': 'Densidad', 'unidad': '', 'ref_min': '1.003', 'ref_max': '1.030'},
        {'parametro': 'Proteínas', 'unidad': 'mg/dL', 'ref_min': '', 'ref_max': '14'},
        {'parametro': 'Glucosa (orina)', 'unidad': 'mg/dL', 'ref_min': '', 'ref_max': '15'},
        {'parametro': 'Leucocitos', 'unidad': 'por campo', 'ref_min': '', 'ref_max': '5'},
        {'parametro': 'Hematíes', 'unidad': 'por campo', 'ref_min': '', 'ref_max': '3'},
    ],
}

NOMBRES_EXAMEN_DEFAULT = {
    'HEMOGRAMA': 'Hemograma / Biometría Hemática Completa',
    'QUIMICA': 'Química sanguínea completa',
    'COAGULACION': 'Perfil de coagulación',
    'MARCADORES': 'Panel de marcadores tumorales',
    'ORINA': 'Uroanálisis completo',
    'CULTIVO': 'Cultivo',
    'IMAGENOLOGIA': 'Estudio de imagen',
    'PATOLOGIA': 'Reporte de anatomía patológica',
    'OTRO': 'Examen de laboratorio',
}
