# Generated by Django 6.0.5 on 2026-06-10 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_paciente_diagnostico_enremision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('HEMOGRAMA', 'Hemograma / BHC'), ('QUIMICA', 'Química sanguínea'), ('COAGULACION', 'Coagulación'), ('ORINA', 'Análisis de orina'), ('CULTIVO', 'Cultivo microbiológico'), ('IMAGENOLOGIA', 'Imagenología'), ('PATOLOGIA', 'Anatomía Patológica'), ('MARCADORES', 'Marcadores tumorales'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('nombre_examen', models.CharField(max_length=200)),
                ('fecha_muestra', models.DateField(db_index=True)),
                ('fecha_resultado', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('REVISADO', 'Revisado'), ('CRITICO', 'Valores críticos')], db_index=True, default='RECIBIDO', max_length=20)),
                ('resultado_narrativo', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='laboratorio/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('hay_valores_criticos', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_laboratorio', to='pacientes.paciente')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_lab_revisados', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_lab_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de laboratorio',
                'verbose_name_plural': 'Resultados de laboratorio',
                'ordering': ['-fecha_muestra', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValorResultado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parametro', models.CharField(max_length=120)),
                ('valor', models.CharField(max_length=100)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('referencia_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('referencia_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('bandera', models.CharField(choices=[('NORMAL', 'Normal'), ('BAJO', 'Bajo'), ('ALTO', 'Alto'), ('CRITICO_BAJO', 'Crítico bajo'), ('CRITICO_ALTO', 'Crítico alto'), ('SIN_RANGO', 'Sin rango')], db_index=True, default='SIN_RANGO', max_length=15)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='laboratorio.resultadolaboratorio')),
            ],
            options={
                'verbose_name': 'Valor de resultado',
                'verbose_name_plural': 'Valores de resultado',
                'ordering': ['orden', 'parametro'],
            },
        ),
        migrations.AddIndex(
            model_name='resultadolaboratorio',
            index=models.Index(fields=['paciente', 'fecha_muestra'], name='lab_pcte_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadolaboratorio',
            index=models.Index(fields=['paciente', 'tipo'], name='lab_pcte_tipo_idx'),
        ),
    ]
