# Generated by Django 6.0.5 on 2026-06-23 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEstudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo de estudio',
                'verbose_name_plural': 'Catálogo de estudios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='valorresultado',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='valorresultado',
            name='referencia_texto',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.CreateModel(
            name='CatalogoParametro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('unidad', models.CharField(blank=True, max_length=60)),
                ('referencia_minima', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('referencia_maxima', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('referencia_texto', models.CharField(blank=True, max_length=180)),
                ('requiere_comentario', models.BooleanField(default=False)),
                ('comentario_sugerido', models.TextField(blank=True)),
                ('alerta_sistema', models.TextField(blank=True)),
                ('alerta_critica', models.BooleanField(db_index=True, default=False)),
                ('tipo_valor', models.CharField(choices=[('numerico', 'Numérico'), ('texto', 'Texto'), ('resultado', 'Resultado'), ('positivo_negativo', 'Positivo/Negativo')], db_index=True, default='numerico', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='laboratorio.catalogoestudio')),
            ],
            options={
                'verbose_name': 'Catálogo de parámetro',
                'verbose_name_plural': 'Catálogo de parámetros',
                'ordering': ['estudio__nombre', 'orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='valorresultado',
            name='parametro_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='laboratorio.catalogoparametro'),
        ),
        migrations.AddIndex(
            model_name='catalogoparametro',
            index=models.Index(fields=['estudio', 'activo'], name='lab_cat_param_est_act_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogoparametro',
            index=models.Index(fields=['tipo_valor'], name='lab_cat_param_tipo_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogoparametro',
            constraint=models.UniqueConstraint(fields=('estudio', 'nombre'), name='lab_catalogo_parametro_unico'),
        ),
    ]
