# Generated by Django 6.0.5 on 2026-05-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_latitud_longitud_centrosalud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrosalud',
            options={'ordering': ['nombre'], 'verbose_name': 'Centro de salud', 'verbose_name_plural': 'Centros de salud'},
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='camas_disponibles',
            field=models.PositiveIntegerField(default=0, verbose_name='Camas oncológicas disponibles'),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='camas_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Camas oncológicas total'),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='entrenados_facci',
            field=models.PositiveIntegerField(default=0, verbose_name='Entrenados FACCI'),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='esp_imagenes_diagnosticas',
            field=models.BooleanField(default=False, verbose_name='Imágenes Diagnósticas'),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='esp_laboratorio_avanzado',
            field=models.BooleanField(default=False, verbose_name='Laboratorio Clínico Avanzado'),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='esp_oncologia_pediatrica',
            field=models.BooleanField(default=False, verbose_name='Oncología Pediátrica'),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='esp_pediatria_general',
            field=models.BooleanField(default=False, verbose_name='Pediatría General'),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='estado_derivacion',
            field=models.CharField(choices=[('disponible', 'Disponible para derivación'), ('limitado', 'Capacidad limitada'), ('no_disponible', 'No disponible'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20, verbose_name='Estado de derivación'),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='medicos_titulares',
            field=models.PositiveIntegerField(default=0, verbose_name='Médicos titulares en turno'),
        ),
        migrations.AlterField(
            model_name='centrosalud',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección exacta'),
        ),
        migrations.AlterField(
            model_name='centrosalud',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del centro'),
        ),
        migrations.AlterField(
            model_name='centrosalud',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia / Ciudad'),
        ),
        migrations.AlterField(
            model_name='centrosalud',
            name='tipo',
            field=models.CharField(choices=[('hospital', 'Nivel 3 (Especializado)'), ('clinica', 'Nivel 2 (General)'), ('unidad_atencion', 'Unidad de Atención Primaria'), ('centro_diagnostico', 'Centro Diagnóstico'), ('otro', 'Otro')], default='hospital', max_length=30),
        ),
    ]
