# Generated by Django 6.0.5 on 2026-06-09 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_centrosalud_capacidades_personal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logactividad',
            options={'ordering': ['-fecha'], 'verbose_name': 'Log de actividad', 'verbose_name_plural': 'Logs de actividad'},
        ),
        migrations.AddField(
            model_name='logactividad',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logactividad',
            name='modulo',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='logactividad',
            name='objeto_repr',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='logactividad',
            name='tipo_accion',
            field=models.CharField(choices=[('CREACION', 'Creacion'), ('EDICION', 'Edicion'), ('ELIMINACION', 'Eliminacion'), ('CONSULTA', 'Consulta'), ('LOGIN', 'Inicio de sesion'), ('LOGOUT', 'Cierre de sesion'), ('REPORTE', 'Generacion de reporte')], db_index=True, default='CONSULTA', max_length=20),
        ),
        migrations.AddIndex(
            model_name='logactividad',
            index=models.Index(fields=['fecha'], name='logactividad_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='logactividad',
            index=models.Index(fields=['tipo_accion'], name='logactividad_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='logactividad',
            index=models.Index(fields=['modulo'], name='logactividad_modulo_idx'),
        ),
    ]
