# Generated by Django 6.0.5 on 2026-06-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logactividad_options_logactividad_direccion_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrosalud',
            name='coordenadas_actualizadas',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='direccion_normalizada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
