# Generated by Django 6.0.5 on 2026-06-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_centrosalud_coordenadas_actualizadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo del sistema')),
                ('nombre_institucion', models.CharField(default='FACCI Care', max_length=150, verbose_name='Nombre de la institución')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuraciones del sistema',
            },
        ),
    ]
