# Generated by Django 6.0.5 on 2026-06-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sistemaconfiguracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaconfiguracion',
            name='logo_aplicacion',
            field=models.ImageField(blank=True, null=True, upload_to='logo_app/', verbose_name='Logo de la aplicación'),
        ),
        migrations.AddField(
            model_name='sistemaconfiguracion',
            name='logo_reportes',
            field=models.ImageField(blank=True, null=True, upload_to='logo_reportes/', verbose_name='Logo oficial para reportes'),
        ),
        migrations.AddField(
            model_name='sistemaconfiguracion',
            name='nombre_aplicacion',
            field=models.CharField(default='FACCI Care', max_length=150, verbose_name='Nombre de la aplicación'),
        ),
        migrations.AlterField(
            model_name='sistemaconfiguracion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo del sistema (Legacy)'),
        ),
        migrations.AlterField(
            model_name='sistemaconfiguracion',
            name='nombre_institucion',
            field=models.CharField(default='Fundación de Apoyo Contra el Cáncer Infantil (FACCI)', max_length=150, verbose_name='Nombre de la institución'),
        ),
    ]
