# Generated by Django 6.0.5 on 2026-05-28 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_paciente', models.CharField(db_index=True, help_text='Código único generado automáticamente (ej. FACCI-20240001)', max_length=20, unique=True, verbose_name='Código de paciente')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de sangre')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('escuela', models.CharField(blank=True, max_length=200, verbose_name='Escuela')),
                ('seguro_medico', models.CharField(blank=True, max_length=100, verbose_name='Seguro médico')),
                ('numero_seguro', models.CharField(blank=True, max_length=50, verbose_name='Número de seguro')),
                ('alergias', models.TextField(blank=True, help_text='Listar alergias separadas por coma', verbose_name='Alergias conocidas')),
                ('antecedentes_medicos', models.TextField(blank=True, help_text='Historial de enfermedades, cirugías y condiciones previas', verbose_name='Antecedentes médicos')),
                ('estado_actual', models.CharField(choices=[('SOSPECHOSO', 'Sospechoso'), ('REFERIDO', 'Referido'), ('EN_ESTUDIO', 'En estudio'), ('CONFIRMADO', 'Confirmado'), ('DESCARTADO', 'Descartado'), ('EN_TRATAMIENTO', 'En tratamiento'), ('FINALIZADO', 'Finalizado')], db_index=True, default='SOSPECHOSO', max_length=20, verbose_name='Estado actual')),
                ('fotografia', models.ImageField(blank=True, upload_to='pacientes/', verbose_name='Fotografía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('medico_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['MEDICO', 'PEDIATRA', 'ONCOLOGO', 'PERSONAL_FACCI']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Médico asignado')),
                ('padre_tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='padres.padretutor', verbose_name='Padre / Tutor')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['codigo_paciente'], name='paciente_codigo_idx'), models.Index(fields=['estado_actual'], name='paciente_estado_idx'), models.Index(fields=['padre_tutor'], name='paciente_padre_idx'), models.Index(fields=['provincia'], name='paciente_provincia_idx')],
            },
        ),
    ]
