# Generated by Django 6.0.5 on 2026-06-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.CharField(blank=True, choices=[('LEUCEMIA', 'Leucemia'), ('TUMORES_SNC', 'Tumores del SNC'), ('RETINOBLASTOMA', 'Retinoblastoma'), ('TUMOR_WILMS', 'Tumor de Wilms'), ('NEUROBLASTOMA', 'Neuroblastoma'), ('OTRO', 'Otro')], db_index=True, default='', max_length=20, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_actual',
            field=models.CharField(choices=[('SOSPECHOSO', 'Sospechoso'), ('REFERIDO', 'Referido'), ('EN_ESTUDIO', 'En estudio'), ('CONFIRMADO', 'Confirmado'), ('DESCARTADO', 'Descartado'), ('EN_TRATAMIENTO', 'En tratamiento'), ('EN_REMISION', 'En remisión'), ('FINALIZADO', 'Finalizado')], db_index=True, default='SOSPECHOSO', max_length=20, verbose_name='Estado actual'),
        ),
    ]
