# Generated by Django 6.0.5 on 2026-06-20 15:48

import apps.core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_diagnostico_enremision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=apps.core.encryption.EncryptedTextField(blank=True, help_text='Listar alergias separadas por coma', verbose_name='Alergias conocidas'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='antecedentes_medicos',
            field=apps.core.encryption.EncryptedTextField(blank=True, help_text='Historial de enfermedades, cirugías y condiciones previas', verbose_name='Antecedentes médicos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=apps.core.encryption.EncryptedTextField(blank=True, verbose_name='Dirección'),
        ),
    ]
