# Generated by Django 6.0.5 on 2026-06-10 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_paciente_diagnostico_enremision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitacionCasa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre / Número')),
                ('capacidad', models.PositiveSmallIntegerField(default=2, verbose_name='Capacidad (personas)')),
                ('descripcion', models.CharField(blank=True, help_text='Planta baja, con baño privado, etc.', max_length=200, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Habilitada')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstanciaFamiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acompanante_nombre', models.CharField(max_length=150, verbose_name='Nombre del acompañante')),
                ('acompanante_parentesco', models.CharField(blank=True, max_length=60, verbose_name='Parentesco')),
                ('acompanante_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del acompañante')),
                ('motivo', models.CharField(choices=[('QUIMIOTERAPIA', 'Ciclo de quimioterapia'), ('CIRUGIA', 'Intervención quirúrgica'), ('RADIOTERAPIA', 'Radioterapia'), ('HOSPITALIZACION', 'Hospitalización prolongada'), ('CONSULTA', 'Consulta / exámenes'), ('OTRO', 'Otro')], default='CONSULTA', max_length=20, verbose_name='Motivo de la estancia')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_egreso_prevista', models.DateField(blank=True, null=True, verbose_name='Fecha de egreso prevista')),
                ('fecha_egreso_real', models.DateField(blank=True, null=True, verbose_name='Fecha de egreso real')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ACTIVA', max_length=12, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estancias', to='pacientes.paciente', verbose_name='Paciente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='alojamiento.habitacioncasa', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Estancia familiar',
                'verbose_name_plural': 'Estancias familiares',
                'ordering': ['-fecha_ingreso'],
                'indexes': [models.Index(fields=['estado'], name='estancia_estado_idx'), models.Index(fields=['paciente'], name='estancia_pcte_idx'), models.Index(fields=['fecha_ingreso'], name='estancia_ingreso_idx')],
            },
        ),
    ]
