# Generated by Django 6.0.5 on 2026-06-24 23:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0002_habitaciones_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaHabitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de entrega')),
                ('hora_ingreso', models.TimeField(blank=True, null=True, verbose_name='Hora de ingreso')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('entregado_por_facci', models.CharField(default='Encargado Administrativo FACCI', max_length=150, verbose_name='Entregado por FACCI')),
                ('recibido_por_familiar', models.CharField(blank=True, max_length=150, verbose_name='Recibido por familiar responsable')),
                ('entregado_por_familiar', models.CharField(blank=True, max_length=150, verbose_name='Entregado por familiar responsable')),
                ('recibido_por_facci', models.CharField(default='Encargado Administrativo FACCI', max_length=150, verbose_name='Recibido por FACCI')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_habitacion_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_habitacion', to='alojamiento.estanciafamiliar', verbose_name='Estancia')),
            ],
            options={
                'verbose_name': 'Entrega de habitacion',
                'verbose_name_plural': 'Entregas de habitacion',
                'ordering': ['-fecha_entrega', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntregaHabitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_item', models.CharField(max_length=80, verbose_name='Item')),
                ('entregado_por_facci', models.BooleanField(default=False, verbose_name='Entregado por FACCI')),
                ('recibido_por_familiar', models.BooleanField(default=False, verbose_name='Recibido del familiar')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observacion')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alojamiento.entregahabitacion', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Item de entrega de habitacion',
                'verbose_name_plural': 'Items de entrega de habitacion',
                'ordering': ['orden', 'nombre_item'],
            },
        ),
        migrations.AddConstraint(
            model_name='entregahabitacion',
            constraint=models.UniqueConstraint(fields=('estancia',), name='entrega_hab_estancia_unica'),
        ),
        migrations.AddConstraint(
            model_name='itementregahabitacion',
            constraint=models.UniqueConstraint(fields=('entrega', 'nombre_item'), name='item_entrega_hab_unico'),
        ),
    ]
