# Generated by Django 6.0.5 on 2026-05-28 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del seguimiento')),
                ('estado_clinico', models.CharField(help_text='Resumen breve del estado del paciente en esta consulta', max_length=200, verbose_name='Estado clínico actual')),
                ('sintomas_actuales', models.TextField(blank=True, verbose_name='Síntomas actuales')),
                ('tratamiento_actual', models.TextField(blank=True, help_text='Descripción del protocolo de tratamiento activo', verbose_name='Tratamiento en curso')),
                ('medicamentos', models.TextField(blank=True, help_text='Lista de medicamentos, dosis y frecuencia', verbose_name='Medicamentos indicados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del médico')),
                ('proxima_cita', models.DateTimeField(blank=True, null=True, verbose_name='Próxima cita')),
                ('requiere_hospitalizacion', models.BooleanField(default=False, verbose_name='Requiere hospitalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Médico tratante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Seguimiento de paciente',
                'verbose_name_plural': 'Seguimientos de pacientes',
                'ordering': ['-fecha_seguimiento'],
                'indexes': [models.Index(fields=['paciente'], name='seguimiento_paciente_idx'), models.Index(fields=['fecha_seguimiento'], name='seguimiento_fecha_idx'), models.Index(fields=['requiere_hospitalizacion'], name='seguimiento_hosp_idx')],
            },
        ),
    ]
