# Generated by Django 6.0.1 on 2026-06-01 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_notaclinica'),
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicacionMedica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_indicacion', models.CharField(choices=[('MEDICACION', 'Medicación'), ('PROTOCOLO_ACTIVO', 'Protocolo Activo'), ('PAUTA_MEDICA', 'Pauta Médica Específica'), ('HIDRATACION', 'Hidratación'), ('DESCANSO', 'Descanso'), ('ALIMENTACION', 'Alimentación'), ('HIGIENE', 'Higiene'), ('OTRA', 'Otra')], default='OTRA', max_length=50, verbose_name='Tipo de indicación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la indicación')),
                ('descripcion', models.TextField(verbose_name='Descripción / Instrucciones')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10, verbose_name='Nivel de prioridad')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_prescritas', to=settings.AUTH_USER_MODEL, verbose_name='Médico tratante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicaciones_medicas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Indicación médica',
                'verbose_name_plural': 'Indicaciones médicas',
                'ordering': ['prioridad', '-created_at'],
            },
        ),
    ]
