# Generated by Django 6.0.5 on 2026-06-01 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_indicacionmedica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientopaciente',
            name='lugar_cita',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lugar / Centro de la cita'),
        ),
        migrations.AddField(
            model_name='seguimientopaciente',
            name='medico_cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_agendadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico de la cita'),
        ),
    ]
