# Generated by Django 6.0.5 on 2026-06-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_seguimientopaciente_lugar_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientopaciente',
            name='fase_protocolo',
            field=models.CharField(choices=[('INDUCCION', 'Inducción'), ('CONSOLIDACION', 'Consolidación'), ('MANTENIMIENTO', 'Mantenimiento'), ('VIGILANCIA', 'Vigilancia')], default='VIGILANCIA', max_length=20, verbose_name='Fase del protocolo'),
        ),
    ]
