# Generated by Django 6.0.5 on 2026-06-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_add_fase_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientopaciente',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='seguimientopaciente',
            name='talla_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)'),
        ),
    ]
