# Generated by Django 6.0.5 on 2026-06-26 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_add_peso_talla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimientopaciente',
            old_name='proxima_cita',
            new_name='proxima_fecha_seguimiento',
        ),
        migrations.RenameField(
            model_name='seguimientopaciente',
            old_name='medico_cita',
            new_name='medico_seguimiento',
        ),
        migrations.RenameField(
            model_name='seguimientopaciente',
            old_name='lugar_cita',
            new_name='lugar_seguimiento',
        ),
        migrations.AlterField(
            model_name='seguimientopaciente',
            name='proxima_fecha_seguimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próximo seguimiento'),
        ),
        migrations.AlterField(
            model_name='seguimientopaciente',
            name='medico_seguimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_agendados', to=settings.AUTH_USER_MODEL, verbose_name='Médico del seguimiento'),
        ),
        migrations.AlterField(
            model_name='seguimientopaciente',
            name='lugar_seguimiento',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lugar / Centro del seguimiento'),
        ),
    ]
