# Generated by Django 6.0.5 on 2026-08-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0008_indicacionmedica_visible_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientopaciente',
            name='temperatura_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AddField(
            model_name='seguimientopaciente',
            name='tension_arterial',
            field=models.CharField(blank=True, help_text='Formato sistólica/diastólica, ej. 110/70', max_length=20, verbose_name='Tensión arterial (mmHg)'),
        ),
    ]
