# Generated by Django 6.0.5 on 2026-05-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(blank=True, default=None, help_text='Cédula de identidad dominicana (ej. 001-0000000-0)', max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
