# Generated by Django 6.0.5 on 2026-06-20 15:48

import apps.core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rol_max_length_nuevos_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=apps.core.encryption.EncryptedCharField(blank=True, help_text='Número de contacto principal', max_length=512, verbose_name='Teléfono'),
        ),
    ]
