# Generated by Django 6.0.5 on 2026-07-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_documento',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], default='CEDULA', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
