# Generated by Django 6.0.5 on 2026-06-10 19:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_paciente_diagnostico_enremision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionPsicosocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_evaluacion', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cuidador_principal_nombre', models.CharField(blank=True, max_length=150)),
                ('parentesco_cuidador', models.CharField(blank=True, choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('ABUELO_A', 'Abuelo/a'), ('TIO_A', 'Tío/a'), ('HERMANO_A', 'Hermano/a mayor'), ('OTRO', 'Otro')], max_length=20)),
                ('personas_en_hogar', models.PositiveSmallIntegerField(default=1, help_text='Número total de personas que viven en el hogar')),
                ('tipo_vivienda', models.CharField(blank=True, choices=[('PROPIA', 'Propia'), ('ALQUILADA', 'Alquilada'), ('PRESTADA', 'Prestada / Cedida'), ('OTRO', 'Otro')], max_length=20)),
                ('ingreso_mensual', models.CharField(choices=[('NINGUNO', 'Sin ingresos'), ('BAJO', 'Menos de RD$8,000/mes'), ('MEDIO', 'RD$8,000 – RD$20,000/mes'), ('SUFICIENTE', 'Más de RD$20,000/mes')], default='MEDIO', max_length=20, verbose_name='Ingreso familiar mensual')),
                ('tiene_seguro_medico', models.BooleanField(default=True, verbose_name='Tiene seguro médico (SFS, ARS o SENASA)')),
                ('dificultad_medicamentos', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('MODERADA', 'Moderada'), ('SEVERA', 'Severa')], default='NINGUNA', max_length=20, verbose_name='Dificultad para costear medicamentos')),
                ('dificultad_transporte', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('MODERADA', 'Moderada'), ('SEVERA', 'Severa')], default='NINGUNA', max_length=20, verbose_name='Dificultad para trasladarse al hospital')),
                ('condicion_vivienda', models.CharField(choices=[('ADECUADA', 'Adecuada'), ('REGULAR', 'Regular'), ('PRECARIA', 'Precaria')], default='ADECUADA', max_length=20, verbose_name='Condición general de la vivienda')),
                ('hacinamiento', models.BooleanField(default=False, verbose_name='Existe hacinamiento (más de 3 personas por habitación)')),
                ('servicios_basicos_ausentes', models.BooleanField(default=False, verbose_name='Faltan servicios básicos (agua potable, luz, saneamiento)')),
                ('apoyo_familiar', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('LIMITADO', 'Limitado'), ('NINGUNO', 'Sin apoyo')], default='BUENO', max_length=20, verbose_name='Red de apoyo familiar')),
                ('cuidador_es_unico', models.BooleanField(default=False, verbose_name='El cuidador es el único responsable (sin red de relevo)')),
                ('estado_emocional_cuidador', models.CharField(choices=[('ESTABLE', 'Estable'), ('VULNERABLE', 'Vulnerable / En riesgo'), ('EN_CRISIS', 'En crisis')], default='ESTABLE', max_length=20, verbose_name='Estado emocional del cuidador principal')),
                ('cuidador_perdio_trabajo', models.BooleanField(default=False, verbose_name='El cuidador perdió o abandonó su empleo por el cuidado')),
                ('cuidador_requiere_apoyo_psicologico', models.BooleanField(default=False, verbose_name='El cuidador requiere apoyo psicológico')),
                ('nino_en_edad_escolar', models.BooleanField(default=True, verbose_name='El paciente está en edad escolar (3–18 años)')),
                ('abandono_escolar', models.BooleanField(default=False, verbose_name='Ha abandonado o interrumpido la escuela por la enfermedad')),
                ('impacto_emocional_paciente', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('SEVERO', 'Severo')], default='LEVE', max_length=20, verbose_name='Impacto emocional observable en el paciente')),
                ('puntaje_total', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Moderado'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], db_index=True, default='BAJO', max_length=10)),
                ('necesidades_identificadas', models.TextField(blank=True)),
                ('acciones_recomendadas', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('requiere_seguimiento_social', models.BooleanField(default=False)),
                ('proxima_evaluacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_psicosociales_realizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_psicosociales', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Evaluación psicosocial',
                'verbose_name_plural': 'Evaluaciones psicosociales',
                'ordering': ['-fecha_evaluacion'],
                'indexes': [models.Index(fields=['paciente', 'fecha_evaluacion'], name='psico_pcte_fecha_idx')],
            },
        ),
    ]
