# Generated by Django 6.0.5 on 2026-05-28 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('LABORATORIO', 'Laboratorio'), ('RADIOGRAFIA', 'Radiografía / Imagen'), ('BIOPSIA', 'Biopsia'), ('ANALITICA', 'Analítica sanguínea'), ('RECETA', 'Receta médica'), ('INFORME_MEDICO', 'Informe médico'), ('OTRO', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo de documento')),
                ('archivo', models.FileField(help_text='PDF, imagen o documento médico', upload_to='documentos/%Y/%m/', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del contenido del documento', verbose_name='Descripción')),
                ('fecha_documento', models.DateField(help_text='Fecha en que fue emitido el documento', verbose_name='Fecha del documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.paciente', verbose_name='Paciente')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento médico',
                'verbose_name_plural': 'Documentos médicos',
                'ordering': ['-fecha_documento'],
                'indexes': [models.Index(fields=['paciente'], name='documento_paciente_idx'), models.Index(fields=['tipo_documento'], name='documento_tipo_idx'), models.Index(fields=['fecha_documento'], name='documento_fecha_idx')],
            },
        ),
    ]
