# Generated by Django 6.0.1 on 2026-05-31 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('pacientes', '0002_notaclinica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentomedico',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('CORRECCION', 'Requiere corrección')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='documentomedico',
            name='tipo_documento',
            field=models.CharField(choices=[('HEMOGRAMA', 'Hemograma'), ('ANALITICA', 'Analítica'), ('RADIOGRAFIA', 'Radiografía'), ('SONOGRAFIA', 'Sonografía'), ('RESONANCIA', 'Resonancia'), ('TOMOGRAFIA', 'Tomografía'), ('BIOPSIA', 'Biopsia'), ('RECETA', 'Receta médica'), ('INFORME_MEDICO', 'Informe médico'), ('REFERIMIENTO', 'Referimiento'), ('OTRO', 'Otro'), ('LABORATORIO', 'Laboratorio')], db_index=True, max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.CreateModel(
            name='SolicitudDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ej: Hemograma completo y plaquetas', max_length=150, verbose_name='Estudio Solicitado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Detalles / Indicaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SUBIDO', 'Subido'), ('REVISADO', 'Revisado'), ('CORRECCION', 'Requiere corrección')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('documento_asociado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_relacionada', to='documentos.documentomedico', verbose_name='Documento Asociado')),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_documento_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico Solicitante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_documento', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Solicitud de documento',
                'verbose_name_plural': 'Solicitudes de documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
