# Generated by Django 6.0.5 on 2026-05-28 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('PACIENTES', 'Pacientes'), ('REFERENCIAS', 'Referencias médicas'), ('CRIBADO', 'Cribado oncológico'), ('SEGUIMIENTO', 'Seguimiento clínico'), ('ESTADISTICAS', 'Estadísticas generales')], db_index=True, max_length=15, verbose_name='Tipo de reporte')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Período desde')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Período hasta')),
                ('archivo', models.FileField(blank=True, help_text='PDF o Excel con los datos del reporte', upload_to='reportes/%Y/%m/', verbose_name='Archivo generado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Generado el')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte generado',
                'verbose_name_plural': 'Reportes generados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo_reporte'], name='reporte_tipo_idx'), models.Index(fields=['generado_por'], name='reporte_usuario_idx')],
            },
        ),
    ]
