# Generated by Django 6.0.5 on 2026-06-23 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='codigo_documento',
            field=models.CharField(blank=True, max_length=40, verbose_name='Codigo del documento'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='formato',
            field=models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel .xlsx'), ('csv', 'CSV')], db_index=True, default='pdf', max_length=10, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='nombre_reporte',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del reporte'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='total_registros',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de registros'),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo_reporte',
            field=models.CharField(choices=[('RESUMEN_MENSUAL', 'Resumen mensual'), ('POR_PROVINCIA', 'Por provincia'), ('POR_DIAGNOSTICO', 'Por diagnostico'), ('SEGUIMIENTO_CASOS', 'Seguimiento de casos'), ('REFERENCIAS_MEDICAS', 'Referencias medicas'), ('PACIENTES', 'Pacientes'), ('REFERENCIAS', 'Referencias médicas'), ('CRIBADO', 'Cribado oncológico'), ('SEGUIMIENTO', 'Seguimiento clínico'), ('ESTADISTICAS', 'Estadísticas generales')], db_index=True, max_length=30, verbose_name='Tipo de reporte'),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['formato'], name='reporte_formato_idx'),
        ),
    ]
