# Generated by Django 6.0.5 on 2026-05-28 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cribado', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaMedica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_destino', models.CharField(max_length=200, verbose_name='Hospital / Centro de destino')),
                ('motivo_referencia', models.TextField(help_text='Descripción clínica que justifica la referencia', verbose_name='Motivo de referencia')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], db_index=True, default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_referencia', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de referencia')),
                ('fecha_cita', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cita agendada')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('cuestionario', models.ForeignKey(blank=True, help_text='Cuestionario que motivó esta referencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_generadas', to='cribado.cuestionariocribado', verbose_name='Cribado de origen')),
                ('especialista_destino', models.ForeignKey(blank=True, help_text='Especialista dentro del sistema que recibirá al paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Especialista destino')),
                ('medico_referente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Médico referente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Referencia médica',
                'verbose_name_plural': 'Referencias médicas',
                'ordering': ['-fecha_referencia'],
                'indexes': [models.Index(fields=['estado'], name='referencia_estado_idx'), models.Index(fields=['prioridad'], name='referencia_prioridad_idx'), models.Index(fields=['paciente'], name='referencia_paciente_idx')],
            },
        ),
    ]
