# Generated by Django 6.0.5 on 2026-06-10 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrarreferencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateField(help_text='Fecha en que el paciente fue atendido en el centro destino', verbose_name='Fecha de atención')),
                ('diagnostico', models.TextField(help_text='Diagnóstico clínico o histopatológico confirmado', verbose_name='Diagnóstico establecido')),
                ('tipo_cancer', models.CharField(blank=True, choices=[('LEUCEMIA', 'Leucemia'), ('TUMORES_SNC', 'Tumores del SNC'), ('RETINOBLASTOMA', 'Retinoblastoma'), ('TUMOR_WILMS', 'Tumor de Wilms'), ('NEUROBLASTOMA', 'Neuroblastoma'), ('LINFOMA', 'Linfoma'), ('SARCOMA', 'Sarcoma'), ('DESCARTADO', 'Sospecha descartada'), ('OTRO', 'Otro / Por definir')], max_length=20, verbose_name='Tipo de cáncer confirmado')),
                ('estadio', models.CharField(choices=[('I', 'Estadio I'), ('II', 'Estadio II'), ('III', 'Estadio III'), ('IV', 'Estadio IV'), ('NE', 'No estadificado / N/A')], default='NE', max_length=3, verbose_name='Estadio clínico')),
                ('tratamiento_realizado', models.TextField(blank=True, help_text='Cirugía, quimioterapia, radioterapia, etc.', verbose_name='Tratamiento realizado / indicado')),
                ('medicamentos_indicados', models.TextField(blank=True, help_text='Fármacos prescritos con dosis y duración', verbose_name='Medicamentos indicados')),
                ('resultado_atencion', models.CharField(choices=[('CONFIRMADO_SEGUIMIENTO', 'Diagnóstico confirmado — en seguimiento FACCI'), ('TRATAMIENTO_INICIADO', 'Tratamiento iniciado'), ('DERIVADO_OTRO_NIVEL', 'Derivado a otro nivel de atención'), ('ALTA_MEDICA', 'Alta médica — descartado'), ('NO_PRESENTADO', 'Paciente no se presentó'), ('FALLECIDO', 'Paciente fallecido')], db_index=True, max_length=30, verbose_name='Resultado de la atención')),
                ('recomendaciones', models.TextField(blank=True, help_text='Indicaciones de seguimiento para el centro de origen', verbose_name='Recomendaciones al médico referente')),
                ('requiere_seguimiento_facci', models.BooleanField(default=True, verbose_name='Requiere seguimiento en FACCI')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Fecha próxima cita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico_contrarreferente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrareferencias_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Médico que emite contrarreferencia')),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrarreferencia', to='referencias.referenciamedica', verbose_name='Referencia de origen')),
            ],
            options={
                'verbose_name': 'Contrarreferencia',
                'verbose_name_plural': 'Contrareferencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
