# Generated by Django 6.0.5 on 2026-06-25 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0003_entregahabitacion_itementregahabitacion_and_more'),
        ('pacientes', '0005_alter_paciente_alergias_and_more'),
        ('referencias', '0002_contrarreferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaIngresoCasaFACCI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centro_origen', models.CharField(blank=True, max_length=200, verbose_name='Centro de origen')),
                ('hospital_destino', models.CharField(default='Casa FACCI', max_length=200, verbose_name='Hospital / destino')),
                ('motivo_ingreso', models.TextField(verbose_name='Motivo de ingreso')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de entrada')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('tiempo_estadia', models.CharField(blank=True, max_length=80, verbose_name='Tiempo estimado de estadia')),
                ('responsable_paciente', models.CharField(blank=True, max_length=150, verbose_name='Responsable del paciente')),
                ('parentesco_responsable', models.CharField(blank=True, max_length=60, verbose_name='Parentesco')),
                ('cedula_responsable', models.CharField(blank=True, max_length=20, verbose_name='Cedula')),
                ('telefono_responsable', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('celular_responsable', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('direccion_responsable', models.TextField(blank=True, verbose_name='Direccion')),
                ('ocupacion_responsable', models.CharField(blank=True, max_length=100, verbose_name='Ocupacion')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('INGRESADO', 'Ingresado'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_casa_facci_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_ingreso', to='alojamiento.habitacioncasa', verbose_name='Habitacion asignada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_casa_facci', to='pacientes.paciente', verbose_name='Paciente')),
                ('referencia_medica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_casa_facci', to='referencias.referenciamedica', verbose_name='Referencia medica')),
            ],
            options={
                'verbose_name': 'Referencia ingreso Casa FACCI',
                'verbose_name_plural': 'Referencias ingreso Casa FACCI',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['paciente'], name='ingreso_casa_paciente_idx'), models.Index(fields=['estado'], name='ingreso_casa_estado_idx'), models.Index(fields=['fecha_entrada'], name='ingreso_casa_entrada_idx')],
            },
        ),
    ]
