# Generated by Django 6.0.5 on 2026-07-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0003_referenciaingresocasafacci'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrarreferencia',
            name='estudios_realizados',
            field=models.TextField(blank=True, help_text='Laboratorios, radiografías, TAC, RMN u otros estudios efectuados', verbose_name='Estudios y/o imágenes realizadas'),
        ),
    ]
